name: painted
description: coloring game with magic and adventure
version: 1.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Image Handling
  image_picker: ^1.0.7
  image: ^4.1.7
  path_provider: ^2.1.2

  # Permissions
  permission_handler: ^12.0.1

  # UI / Animation / Effects
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  animate_do: ^4.2.0
  flutter_animate: ^4.5.0
  confetti: ^0.8.0
  rive: ^0.13.20

  # Audio
  audioplayers: ^6.5.0

  # Parsing / Math / Utils
  xml: ^6.5.0
  path_drawing: ^1.0.1
  vector_math: ^2.1.4
  collection: ^1.18.0
  http: ^1.5.0
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: 2.6.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/previews/
    - assets/data/
    - assets/audio/
    - assets/scenes/
    - assets/svg/
    - assets/svg/TasaiYumeForeground.svg
    - assets/svg/valley.svg
    - assets/svg/magic/
    - assets/svg/magic/farm/
   
    - assets/animations/  # Can now include .riv files here if needed

# fonts:
#   - family: YourCustomFont
#     fonts:
#       - asset: assets/fonts/YourFont-Regular.ttf
#       - asset: assets/fonts/YourFont-Bold.ttf
#         weight: 700
